#!/bin/bash
#
#   tulizu: View and customize ASCII art included /etc/issue files
#
#   Copyright (C) 2016 loh.tar@googlemail.com
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#   MA 02110-1301, USA.

# shellcheck disable=SC2034  # Unused variables - See HINT at the colors

declare -r myName="tulizu"
declare -r myVersion="0.2" # Okt 2017
declare -r myDescription="View and customize ASCII art included /etc/issue files"
declare -r issuePath="/usr/share/$myName/issue"
declare -r tizuPath="/usr/share/$myName/tizu"
declare    powerTool="" # May be set to sudo, doas, run0
declare    tmpFile="$myName-generated.issue"
# As far as I the FHS understood can we place here our tmp file
# FIXME: When FHS 3 is common used change to /run/user/...
declare    tmpPath="/var/run/user/$UID"
declare    pattern              # Search pattern by doc and list

# More about colors at Arch Wiki
# wiki.archlinux.org/index.php/Color_Bash_Prompt
# A full list of escape codes is on Wikipedia
# https://en.wikipedia.org/wiki/ANSI_escape_code#Select_Graphic_Rendition_parameters
# HINT: shellcheck complains about most of these color declarations, but we use these indirect
declare -r Normal=$'\e[0m'      # All attributes off, it should have been better called Reset
declare -r Bold=$'\e[1m'        # Or bright, increased intensity, depend on your terminal
declare -r Faint=$'\e[2m'       # Faint, decreased intensity, or dim
declare -r UScore=$'\e[4m'      # Underscore
declare -r NoScore=$'\e[24m'    # Neither singly nor doubly underlined
declare -r Blink=$'\e[5m'
declare -r NoBlink=$'\e[25m'    # Turn blinking off
declare -r Invert=$'\e[7m'      # or Reverse video
declare -r NotInv=$'\e[27m'     # Not Invert
declare -r Regular=$'\e[22m'    # Normal intensity, Neither bold nor faint; color changes where intensity is implemented as such
declare -r DefFore=$'\e[39m'    # Default foreground color
declare -r DefBack=$'\e[49m'    # Default background color

# Foreground colors
declare -r Black=$'\e[30m'
declare -r Red=$'\e[31m'
declare -r Green=$'\e[32m'
declare -r Yellow=$'\e[33m'
declare -r Blue=$'\e[34m'
declare -r Magenta=$'\e[35m'
declare -r Cyan=$'\e[36m'
declare -r White=$'\e[37m'

# Background colors
declare -r onBlack=$'\e[40m'
declare -r onRed=$'\e[41m'
declare -r onGreen=$'\e[42m'
declare -r onYellow=$'\e[43m'
declare -r onBlue=$'\e[44m'
declare -r onMagenta=$'\e[45m'
declare -r onCyan=$'\e[46m'
declare -r onWhite=$'\e[47m'

# FIXME: Arch wiki says 'If you have an old /etc/issue that has the "clear TTY" escape sequences..'
#        So is it obsolete and/or deprecated? wiki.archlinux.org/index.php/Disable_clearing_of_boot_messages
declare    clearScreen=$'\e\[H\e\[2J'

# Will filled with tizu file settings
declare -A colorSets
declare -A optName
declare -A optDesc
declare -A optCounter
declare -A attributes

#
# Helper Functions
#
print() { printf "%s\n" "$*"; }
info() { printf "$myName: %s\n" "$*" >&2; }
warn() { printf "${Yellow}WARNING $Normal$myName: %s\n" "$*" >&2; }

exitError() {
  local func=${2:-${FUNCNAME[1]:3}}

  [[ $func == '--' ]] && unset func || func="$func: "

  printf "${Red}ERROR $Normal$myName: $func%s\n" "$1" >&2
  exit 1
}

checkFile() {
  if [[ -z $1 ]]; then
    exitError "Need ${2,,} file" "${FUNCNAME[1]:3}" # $2 to lower case
  elif [[ ! -f "$1" ]]; then
    exitError "$2 file not found: $1" "${FUNCNAME[1]:3}"
  fi
}

runAsRoot() {
  # We don't necessarily have to be root, we just need the right to change the issue file
  # because we never run commands as root where more power is needed
  if [[ ! -w /etc/issue && -z $powerTool ]] ; then
    for tool in sudo doas run0 ; do
      powerTool=$(command -v "$tool")
      [[ -n $powerTool ]] && break
    done

    if [[ -z $powerTool ]] ; then
      exitError "No privilege escalation tool found! Tried: sudo doas run0" "${FUNCNAME[1]:3}"
    fi

    info "Use privilege escalation tool: $powerTool"
  fi

  info "Run command: $*"
  # No quoting of "$powerTool" or it won't work if tulizu is run directly by root
  $powerTool "$@"
}

parseTizuFile() {
  local inFile=$1

  colorSets=()
  optName=()
  optDesc=()
  optCounter=()
  attributes=()

  while IFS='=' read -r lhs rhs
  do
    [[ -z $lhs || -z $rhs ]] && continue
    rhs="${rhs%%\#*}"             # Del in line right comments
    rhs="${rhs%"${rhs##*[^ ]}"}"  # Del trailing spaces
    tag=${lhs#:tu# }              # Well, right half of the tag without ':tu# '

    case $tag in
      Author)     attributes[$tag]=$rhs                               ; ;;
      Colors?)    colorSets[$tag]=$rhs                                ; ;;
      Colors)     colorSets["${tag}1"]=$rhs                           ; ;;
      Razor?)     optDesc["z${tag:5}"]=$rhs; (( optCounter["z"]++ ))  ; ;;
      Desc)       attributes[$tag]=$rhs                               ; ;;
      Opt:[a-z])  optName[${tag:4}]=$rhs                              ; ;;
      [a-z][1-9]) optDesc[${tag}]=$rhs; (( optCounter[${tag%?}]++ ))  ; ;;
    esac

  done < "$inFile"

  # Special treatment for Colors because of optional number suffix
  optCounter['c']=${#colorSets[@]}

  if [[ -z ${optName['c']} && ${optCounter['c']} -gt 1 ]]; then
    optName['c']="Color sets"
  elif [[ -z ${optName['c']} && ${optCounter['c']} -gt 0 ]]; then
    optName['c']="Color set"
  fi

  if [[ -z ${optName['z']} && ${optCounter['z']} -gt 1 ]]; then
    optName['z']="Razor cuts"
  elif [[ -z ${optName['z']} && ${optCounter['z']} -gt 0 ]]; then
    optName['z']="Razor cut"
  fi
}

makePattern() {
  pattern=${1:-'*'}
  # find will warn when / is in pattern
  if [[ "$pattern" =~ ^[-_.0-9a-zA-Z]*$ ]]; then
    pattern=${pattern//./*}
    pattern="*$pattern*"
  elif [[ $pattern != '*' ]]; then
    exitError "Only letters, numbers and -._ are allowed as pattern" "${FUNCNAME[1]:3}"
  fi
}

#
# Command Implementations
#
cmdDoc() {
  local docMatch
  local docPath="/usr/share/doc/$myName"

  makePattern "$1"

  mapfile -t docMatch < <(find "$docPath" -not -type d -iname "$pattern" | sort)

  if [[ ${#docMatch[@]} -gt 1 ]]; then
    print "Available documentation:"
    for doc in "${docMatch[@]}" ; do
      doc="${doc#*/??_}"
      print "  ${doc%.*}"
    done
    if [[ -n $1 ]]
      then print "Give a more precise pattern than '$1' to show a file"
      else print "Give a pattern to show a file"
    fi
  elif [[ ${#docMatch[@]} == 0 ]]; then
      print "No manual match '$1'"
  else
   less "${docMatch[0]}"
  fi
}

cmdHelp() {
    ind="  " # indent
    tab=$'\t'
    echo "This is ${myName} (v${myVersion}) - ${myDescription}"
    echo "Usage:"
    echo "${ind}${0##*/} <command> [<argument>]"
    echo "Commands are:"
    echo "${ind}doc, d [<pattern>]${tab}List or show documentation files"

    [[ $1 == "fullHelp" ]] && helpTxt="You read it now" || helpTxt="Give some more help"
    echo "${ind}help, h${tab}${tab}$helpTxt"

    echo "${ind}ekam, e <inFile>${tab}Create a tizu file out of <inFile> and print the file name"
    echo "${ind}install, i [<file>]${tab}Install <file> as /etc/issue. Default file is <tmpFile>"
    echo "${ind}list, l [<pattern>]${tab}List issue files shipped with $myName matching <pattern>"
    echo "${ind}make, m <inFile>${tab}Create new issue file"
    echo "${ind}restore, r${tab}${tab}Restore /etc/issue file from backup /etc/issue.saved-by-$myName"
    echo "${ind}show, s [<file>]${tab}Show <file> or current /etc/issue file"

    [[ $1 != "fullHelp" ]] && return

    echo
    echo "The <pattern> supports only the dot as wildcard which will replaced by an asterisk"
    echo "The <tmpFile> is $tmpPath/$tmpFile and generated by list or make"
    echo
    echo "Commands which take additional options (may prefixed by --):"
    echo "${ind}list"
    echo "${ind}${ind}file, f${tab}${tab}Print only a list of files with full path"
    echo "${ind}${ind}info, i${tab}${tab}Print details about files, like <fileOpt>"
    echo "${ind}${ind}show, s [<fileOpt>]${tab}Display files in a gallery instead of text list"
    echo "${ind}Use the long version with hyphen to distinguish from <pattern>"
    echo
    echo "${ind}make"
    echo "${ind}${ind}tofile <outFile>${tab}Create new issue file as <outFile> insted of <tmpFile>"
    echo "${ind}${ind}opt <fileOpt>${tab}Set option supported by <inFile>"
    echo "${ind}${ind}nohint${tab}${tab}Print no info header"
    echo "${ind}${ind}noshow${tab}${tab}Print nothing, just write file"
    echo
    echo "Examples:"
    echo "${ind}Display all about available files matching 'letter':"
    echo "${ind}${ind}$myName list letter info"
    echo
    echo "${ind}Show available files matching 'logo' with color option 3:"
    echo "${ind}${ind}$myName list logo show c3"
    echo
    echo "${ind}Install a file of your taste with all colors removed:"
    echo "${ind}${ind}$myName l foo.bar s c0"
    echo "${ind}${ind}$myName i             # you will prompted to become root"
    echo
    echo "${ind}Generate an issue file out of your own tizu:"
    echo "${ind}${ind}$myName m your.tizu --opt c3 x2 --tofile your-color3-x-variant2.issue"
    echo
    echo "${ind}Create a tizu template file that you need to edit further out of some ASCII art file:"
    echo "${ind}${ind}$myName ekam some-ascii-art.file"
}

cmdInstall() {
  local file=${1:-"$tmpPath/$tmpFile"}
  local searchPath=("$PWD" "$tmpPath" "$issuePath")
  local -i ok=0

  if [[ -r "$file" ]]; then
    ok=1
  else
    for path in "${searchPath[@]}"; do
      local fullPath="${path}/${file}"
      if [[ -r "${fullPath}" ]]; then
        ok=1
        file=$fullPath
        break
      fi
    done
  fi

  if (( !ok )); then
    exitError "File not found: $file"
  fi

  if [[ ! -f "/etc/issue.saved-by-$myName" ]]; then
    runAsRoot "mv" "/etc/issue" "/etc/issue.saved-by-$myName"
  fi

  runAsRoot "cp" "$file" "/etc/issue"
}

cmdList() {
  local subcmd="list"
  local showOpt=()

  makePattern "$1"

  if [[ "$pattern" =~ ^\*--.*$ ]]
    then pattern="*"
    else shift
  fi

  while [[ $# -gt 0 ]]; do
    case "$1" in
      file|f|--file)
          subcmd="file"
        ;;
      info|i|--info)
          subcmd="info"
        ;;
      show|s|--show)
          subcmd="show"
          showOpt[0]="--opt"
          shift
          while [[ $# -gt 0 ]]; do
            showOpt[${#showOpt[@]}]=$1
            [[ "$2" =~ ^-- ]] && break
            shift
          done;
          [[ ${#showOpt[@]} == 1 ]] && unset showOpt
        ;;
      *)
          exitError "Unknown option: $1"
      ;;
    esac
    shift
  done

  mapfile -t fileMatch < <(find "$issuePath" "$tizuPath" -type f -iname "$pattern" | sort)
  [[ ${#fileMatch[@]} == 0 ]] && exitError  "No file match: ${pattern:1:-1}"

  local fileType

  for file in "${fileMatch[@]}" ; do
    case $subcmd in
      file)
          print "$file"
        ;;
      info|list)
          local separator=1
          if [[ $fileType != "${file##*.}" ]]; then
            [[ -n $fileType ]] && print
            fileType=${file##*.}
            print "Available $fileType files:"
            unset separator
          fi

          parseTizuFile "$file"

        ;;&
      info)
          [[ -n $separator ]] && print
#           file="${file##*/}"
          local name=${file##*/}; name=${name%.*}
          print "  Name: $name"
          [[ -n ${attributes['Author']} ]] && print "  Author: ${attributes['Author']}"
          [[ -n ${attributes['Desc']} ]] && print "  Desc: ${attributes['Desc']}"
          print "  File: ${file}"

          for op in "${!optCounter[@]}"; do
              [[ -n ${optName[$op]} ]] && print "  Option $op: ${optCounter[$op]} ${optName[$op]}"
              if [[ $op == 'c' ]]; then
                for (( i=0; i < ${#colorSets[@]}; i++ )); do
                  d="c$((i+1))"
                  printf "  %s: %s" "$d" "${optDesc[$d]}"
                  # Translate the color-set by eval into escape codes defined at top of this file
                  IFS=" " read -r -a colors <<< "$(eval "echo ${colorSets["Colors$((i+1))"]}")"
                  pattern=("foo" "bar" "baz" "raz" "faz" "taz" "haz")
                  local info=""
                  for (( j=0; j < ${#colors[@]}; j++ )); do
                    info="$info  $Normal${colors[j]}${pattern[j%7]}"
                  done
                  print "$info$Normal"
                done
              else
                for (( i=0; i < ${optCounter[$op]}; i++ )); do
                  d="$op$((i+1))"
                  print "  $d: ${optDesc[$d]}"
                done
            fi
          done
        ;;
      list)
          file="${file##*/}"
          print "  ${file%.*}"
          local ind="        "
          [[ -n ${attributes['Desc']} ]] && print "$ind${attributes['Desc']}"

          for op in "${!optCounter[@]}"; do
              [[ ${optCounter[$op]} -gt 1 ]] && print "$ind$op: ${optCounter[$op]} ${optName[$op]}"
          done
          ;;
      show)
          print ">>> $file"
          cmdShow "$file" "--nohint" "${showOpt[@]}"
          print "<<<"
        ;;
      *)
        exitError "Unknown argument: $subcmd"
        ;;
    esac
  done
}

cmdMake() {
  local    inFile=$1
  local    outFile="$tmpPath/$tmpFile"
  local    hint="yes"
  local    show="yes"
  local -A givenOpt
  local -a givenRazors

  checkFile "$inFile" "Source"

  shift
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --nohint|nohint)
          hint="no"
        ;;
      --noshow|noshow)
          show="no"
        ;;
      --tofile|tofile)
          shift
          outFile="$1"
        ;;
      --opt|opt)
          shift
          while [[ $# -gt 0 ]]; do
            givenOpt["${1:0:1}"]="${1:1}"
            [[ "${1:0:1}" == "z" ]] && givenRazors+=("$1")
            [[ "$2" =~ ^-- ]] && break;
            shift
          done
        ;;
      *)
          exitError "Unknown argument: $1"
        ;;
    esac
    shift
  done

  parseTizuFile "$inFile"

  local -A useOpt
  for op in "${!givenOpt[@]}"; do
    if [[ "${!optCounter[*]}" == *"$op"* ]]
      then useOpt[$op]=${givenOpt[$op]}
      else warn "File has no option: $op"
    fi
  done

  # Set needed but not given options to a default of 1
  for op in "${!optCounter[@]}"; do
    [[ $op == "z"  ]] && continue  # Ignore Razor!
    [[ -z ${useOpt[$op]}  ]] && useOpt[$op]="1"
  done

  # Translate the chosen color-set by eval into escape codes defined at top of this file
  IFS=" " read -r -a colors <<< "$(eval "echo ${colorSets["Colors"${useOpt['c']}]}")"

  if [[ $hint == "yes" ]]; then
    print "Generate file: $outFile"
    print "Use tizu file: $inFile"
    info="Use options: "
    for op in "${!useOpt[@]}"; do
      info="$info$op${useOpt[$op]}  "
    done
    print "$info"

    if [[ ${#optCounter[@]} -gt 0 ]]; then
      for op in "${!useOpt[@]}"; do
        info="$info$op${useOpt[$op]}  "
        print "Option $op: ${optCounter[$op]} ${optName[$op]}"
      done
    fi

    info="Number of defined colors: ${#colors[@]} "
    pattern=("foo" "bar" "baz" "raz" "faz" "taz" "haz")
    for (( i=0; i < ${#colors[@]}; i++ )); do
      info="$info  $Normal${colors[i]}${pattern[i%7]}"
    done
    print "$info$Normal"
  fi

  # Build variable sed scripts
  for op in "${!useOpt[@]}"; do
    [[ $op == 'c' ]] && continue # Ignore color option here
    [[ $op == 'z' ]] && continue # Ignore razor option here
    keepOptions="s/:tu# $op${useOpt[$op]} *://g ; $keepOptions"
  done
  for op in "${givenRazors[@]}"; do
    razorActions="s/:tuR${op:1} *:.*:tuR${op:1} *://g ; $razorActions"
  done

  if (( ${#colors[@]} == 0 )) ; then
    # User forces not to use colors at all
    setColors="s/:tuC[0-9]* *:/$Normal/g ; $setColors"
  fi
  for (( i=0; i < ${#colors[@]}; i++ )); do
    j=$(( i+1 ))
    setColors="s/:tuC$j *:/$Normal${colors[i]}/g ; $setColors"
  done
  # Remove the trailing semicolon
  keepOptions=${keepOptions%;*}
  setColors=${setColors%;*}

  sed -e "$keepOptions                         # Do it first, and then..."       \
      -e "/:tu#/d                              # ...remove remaining comments"   \
      -e "$setColors                           # Now we have less colors to set" \
      -e "$razorActions                        # Cut between Razor-Tags"         \
      -e "s/:tuR[1-9] *://g                    # Remove not activated Razor Tags"\
      -e "s/:tuClearScreen:/$clearScreen/g     #                              "  \
      -e "s/:tuNC *:/$Normal/g                 #                              "  \
      -e "s/:tuAB *:/$Bold/g                   #                              "  \
      -e "s/:tuAF *:/$Faint/g                  #                              "  \
      -e "s/:tuAR *:/$Regular/g                #                              "  \
      -e "s/:tuAU *:/$UScore/g                 #                              "  \
      -e "s/:tuAu *:/$NoScore/g                #                              "  \
      -e "s/:tuAI *:/$Invert/g                 #                              "  \
      -e "s/:tuAi *:/$NotInv/g                 #                              "  \
      -e "s/:tuAK *:/$Blink/g                  #                              "  \
      -e "s/:tuAk *:/$NoBlink/g                #                              "  \
      -e "s/:tuDC *:/$DefFore/g                #                              "  \
      -e "s/:tuDB *:/$DefBack/g                #                              "  \
      -e 's/\\/\\\\/g                          # Double all backslashes...'      \
   -r -e 's/\\\\([46bdesSlmnoOrtuUv])/\\\1/g   # ...but keep issue escapes'      \
      -e "s/[[:space:]]*$//                    # Remove all trailing whitespace" \
      -e "/./!d                                # Remove all empty lines!"        \
      -e "s/:tuDY *://g                        # Remove Dummy at the very last"  \
      "$inFile" > "$outFile"

  [[ "$show" == "yes" ]] && cmdShow "$outFile"
}

cmdEkam() {
  local inFile=$1
  local outFile="$tmpPath/$myName-ekam-generated.tizu"

  checkFile "$inFile" "Source"

  # Create a nice handy header, so the file is working
  cat << 'EOF' > "$outFile"
:tu# Author=Your ID
:tu# Desc=A nice Text
:tu# <Don't hesitate to add more info or credits as comment>
:tu#
:tu# Tip: You may want to re-order/re-number the color tags by some S&R. To avoid trouble
:tu#      you may first rename all :tuC to :tuX and then one by one :tuX<n> to :tuC<m>
:tu#
EOF

  # We replace ASCII codes with Color-Tags in two runs which look almost the
  # same, strange, hu? tulizu uses a concatenation of single escape codes to
  # build 'complex colors' like bold-red. This is here and now counted as two
  # colors and we fix that in the second run. Smarter software concatenate
  # bold-red as only one escape code, which is counted here as one color
  (( i=1 ))
  declare -A tagXColor
  # Replacing color escape codes is cumbersome, we need to escape them
  # Thanks to https://stackoverflow.com/a/29613573
  script='s/[^^]/[&]/g; s/\^/\\^/g'
  # This simplified regex match any escape-m ASCII code, not only colors
  for asciiCode in $(grep -Eo $'\e\[([;0-9]*m)' "$inFile" |sort|uniq) ; do
    escAsciiCode=$(sed "$script" <<<"$asciiCode")
    replaceAsciiCodes="s/$escAsciiCode/:tXC$i:/g ; $replaceAsciiCodes"
    colVar=""
    # escAsciiCode looks like "ESC[0;34;5;40;100m" we cut first two "ESC["  char
    # and replace "m" by ";" so we have then "0;34;5;40;100;" ready to ...
    escRawCode=${asciiCode:2}; escRawCode="${escRawCode/m/;}"
    if [[ "$escRawCode" =~ ^[34]8.+ ]] ; then
      exitError "File uses RGB color settings. Not supported, sorry!"
    fi
    # ...read code-number by code-number
    while read -r -d';' code ; do
      case $code in
          # tulizu prefix each color anyway with $Normal, to avoid unneeded long and ugly
          # color-strings we omit Normal here and deal later with it, see below
          0) true                                                           ; ;;
        # 0) colVar="${colVar}\$Normal"                                     ; ;;

          # Attributes
          1) colVar="${colVar}\$Bold"                                       ; ;;
          2) colVar="${colVar}\$Faint"                                      ; ;;
          4) colVar="${colVar}\$UScore"                                     ; ;;
         24) colVar="${colVar}\$NoScore"                                    ; ;;
          5) colVar="${colVar}\$Blink"                                      ; ;;
         25) colVar="${colVar}\$NoBlink"                                    ; ;;
          7) colVar="${colVar}\$Invert"                                     ; ;;
         27) colVar="${colVar}\$NotInv"                                     ; ;;
         22) colVar="${colVar}\$Regular"                                    ; ;;
         39) colVar="${colVar}\$DefFore"                                    ; ;;
         49) colVar="${colVar}\$DefBack"                                    ; ;;
         # Classic color codes
         30) colVar="${colVar}\$Black"                                      ; ;;
         31) colVar="${colVar}\$Red"                                        ; ;;
         32) colVar="${colVar}\$Green"                                      ; ;;
         33) colVar="${colVar}\$Yellow"                                     ; ;;
         34) colVar="${colVar}\$Blue"                                       ; ;;
         35) colVar="${colVar}\$Magenta"                                    ; ;;
         36) colVar="${colVar}\$Cyan"                                       ; ;;
         37) colVar="${colVar}\$White"                                      ; ;;
         40) colVar="${colVar}\$onBlack"                                    ; ;;
         41) colVar="${colVar}\$onRed"                                      ; ;;
         42) colVar="${colVar}\$onGreen"                                    ; ;;
         43) colVar="${colVar}\$onYellow"                                   ; ;;
         44) colVar="${colVar}\$onBlue"                                     ; ;;
         45) colVar="${colVar}\$onMagenta"                                  ; ;;
         46) colVar="${colVar}\$onCyan"                                     ; ;;
         47) colVar="${colVar}\$onWhite"                                    ; ;;
         # We can "bright" foreground colors build this way..
         90) colVar="${colVar}\$Bold\$Black"                                ; ;;
         91) colVar="${colVar}\$Bold\$Red"                                  ; ;;
         92) colVar="${colVar}\$Bold\$Green"                                ; ;;
         93) colVar="${colVar}\$Bold\$Yellow"                               ; ;;
         94) colVar="${colVar}\$Bold\$Blue"                                 ; ;;
         95) colVar="${colVar}\$Bold\$Magenta"                              ; ;;
         96) colVar="${colVar}\$Bold\$Cyan"                                 ; ;;
         97) colVar="${colVar}\$Bold\$White"                                ; ;;
        # ..but background is messy, so we keep it simple
        100) colVar="${colVar}\$onBlack"                                    ; ;;
        101) colVar="${colVar}\$onRed"                                      ; ;;
        102) colVar="${colVar}\$onGreen"                                    ; ;;
        103) colVar="${colVar}\$onYellow"                                   ; ;;
        104) colVar="${colVar}\$onBlue"                                     ; ;;
        105) colVar="${colVar}\$onMagenta"                                  ; ;;
        106) colVar="${colVar}\$onCyan"                                     ; ;;
        107) colVar="${colVar}\$onWhite"                                    ; ;;
        *) warn "Not supported ESC code $code - Have it marked as 'x${code}x'"
           printf ":tu# FIXME: Not supported ESC color code %s - Search here for 'x%sx'\n" "$code" "$code" >> "$outFile"
           unknownEScFound="1"
           colVar="${colVar}\$x${code}x"; ;;
      esac
    done < <(printf %s "${escRawCode}")

    tagXColor["tXC$i"]="$colVar"
    (( i++ ))
  done

  # We want a nice looking and helpful file
  if [[ -n $unknownEScFound ]] ; then
    cat << EOF >> "$outFile"
:tu#
:tu# Escape codes can be found e.g. at Wikipedia
:tu#     https://en.wikipedia.org/wiki/ANSI_escape_code#Select_Graphic_Rendition_parameters
:tu# You may want to fix your source file and re-run the ekam command
:tu# or fix here the dummy variable(s)
:tu#
:tu#
EOF
  fi

  # Here is the beef! First course with dummy/placeholder Color-Tags
  sed -e "$replaceAsciiCodes" \
      -e "s/$clearScreen/:tuClearScreen:/g      # Just for completeness" \
      -e 's/\\\\/\\/g                           # Make double backslashes single ones' \
      -e 's/^$/:tuDY:/g                         # Fill empty lines so then will later not auto-removed' \
      "$inFile" >> "$outFile"

  # Crunch successive dummy tags into one tag, like ":tXC1::tXC8::tXC3:" ==> ":tuC4:"
  (( i=1 ))
  for tags in $(grep -Eo "(:tXC[0-9]+:)+" "$outFile" |sort|uniq) ; do
    replaceTags="s/$tags/:tuC$i:/g ; $replaceTags"
    fullColor=""
    while read -r -d':' tagX ; do
      [[ -z $tagX ]] && continue
      fullColor="${fullColor}${tagXColor["$tagX"]}"
    done < <(printf %s "${tags}")
    # Now take care for Normal-Only colors
    [[ -z $fullColor ]] && fullColor="\$Normal"
    # Let's add a numbering to the list of colors in the color set to make it easier to identify a color
    while (( ${#fullColor} < 7 )) ; do fullColor="${fullColor} "; done
    allColors="${allColors}${fullColor} "
    (( padSize = ${#fullColor} - 3 - ${#i}))
    # Fill padding with blanks https://stackoverflow.com/a/5349842
    # shellcheck disable=SC2046 # We want word splitting here
    printf -v padding ' %.0s' $(eval "echo {1.."$((padSize))"}");
    colorNumberIdx="${colorNumberIdx}tuC${i}${padding} "
    (( i++ ))
  done

  # All that work for the two or three lines
  cat << EOF >> "$outFile"
:tu#
:tu# c1=Origial colors as auto detected
:tu# Colors1=${allColors}
:tu#          ${colorNumberIdx}
:tu#
EOF

  # Here is the beef! Second course with final Color-Tags
  sed -e "$replaceTags" \
      -e "s/[[:space:]]*$//    # Remove all trailing whitespace" \
      -i "$outFile"

  info "Created: $outFile"
}

cmdRestore() {
  checkFile "/etc/issue.saved-by-$myName" "Backup"
  runAsRoot "mv" "/etc/issue.saved-by-$myName" "/etc/issue"
}

cmdShow() {
  local file=${1:-/etc/issue}
  local hint=${2:-'yes'}

  checkFile "$file" "Issue"

  if [[ $file == *.tizu ]]; then
    [[ $hint == "yes" ]] && info "It's a .tizu file? I run 'make' for you..."
    cmdMake "$@" --tofile "$tmpPath/$tmpFile"
    return
  fi

  if [[ $gettyCanShow == "yes" ]]; then
    # We have to take care of the possible clear screen sequence
    sed -e "s/$clearScreen//g" "$file" > "$tmpPath/$tmpFile-extra"
    agetty --show-issue --issue-file "$tmpPath/$tmpFile-extra"
    rm "$tmpPath/$tmpFile-extra"
    return
  fi

  # Do not init variables twice
  if [[ -z $escDate ]]; then
    # See manpage of agetty below 'ISSUE ESCAPES'
    escIp4="192.168.123.45"           # \4 FIXME: Fill with non fake data
    # TODO \6
    # TODO \b
    escDate=$(date +'%a %b %e %Y')    # \d FIXME: On my machine differs the real replacement
    escSysName=$(uname -s)            # \s
    # TODO \S
    escTTY="tty1"                     # \l FIXME: ...to show a real name
    escArch=$(uname -m)               # \m
    escHostName=$(uname -n)           # \n
    if command -v hostname >/dev/null 2>&1  # \o 'hostname -d' is not always available
      then escNISDomain=$(hostname -d)
      else escNISDomain="(none)"
    fi
    # TODO \O
    escReleaeOS=$(uname -r)           # \r
    escTime=$(date +%T)               # \t
    escUser=$(who | wc -l)            # \u
    escUserS=$([[ $escUser -eq 1 ]] && echo "$escUser user" || echo "$escUser users" )  # \U
    # TODO \v
  fi

  # shellcheck disable=SC2154 # foo is referenced but not assigned - Yeah, it's in a comment as place holder
  sed -e 's/\\\\/\\/g'             \
      -e "s/$clearScreen//g"       \
      -e "s/\\\\4/$escIp4/g"       \
      -e "# TODO s/\\\\6/$foo/g"   \
      -e "# TODO s/\\\\b/$foo/g"   \
      -e "s/\\\\d/$escDate/g"      \
      -e "s/\\\\s/$escSysName/g"   \
      -e "s/\\\\l/$escTTY/g"       \
      -e "s/\\\\m/$escArch/g"      \
      -e "s/\\\\n/$escHostName/g"  \
      -e "s/\\\\o/$escNISDomain/g" \
      -e "# TODO s/\\\\O/$foo/g"   \
      -e "s/\\\\r/$escReleaeOS/g"  \
      -e "s/\\\\t/$escTime/g"      \
      -e "s/\\\\u/$escUser/g"      \
      -e "s/\\\\U/$escUserS/g"     \
      -e "# TODO s/\\\\b/$foo/g"   \
      "$file"
}

#
# Main
#

# Newer versions of agetty can show itself an issue file, so we do not
# need to fake some output
if command -v agetty >/dev/null 2>&1 &&  agetty --help|grep -q -- "--show-issue"
  then gettyCanShow="yes"
  else gettyCanShow="no"
fi

cmd=$1 && shift
case $cmd in
  doc|d)      cmdDoc "$@"                                             ; ;;
  -h|\?|-\?)  cmdHelp                                                 ; ;;
  help|h)     cmdHelp "fullHelp"                                      ; ;;
  install|i)  cmdInstall "$@"                                         ; ;;
  list|l)     cmdList "$@"                                            ; ;;
  make|m)     cmdMake "$@"                                            ; ;;
  ekam|e)     cmdEkam "$@"                                            ; ;;
  restore|r)  cmdRestore                                              ; ;;
  show|s)     cmdShow "$@"                                            ; ;;
  '')         info "Hello! Try -h or h to get some help"              ; ;;
  *)          exitError "Unknown command '$cmd', try -h or h" '--'    ; ;;
esac
